name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Manual run
  workflow_dispatch:

jobs:
  build:
    name: testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install nmslib
          python -m pip install dgl -f https://data.dgl.ai/wheels/repo.html
          python -m pip install -e .

      - name: Install dataclasses for python3.6
        run: python -m pip install dataclasses
        if: matrix.python-version == '3.6'

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          flake8  --count --show-source --statistics --max-line-length=120 --ignore=E203,F811,F401,W503,W504 libreco/ libserving/ tests/ examples/

      - name: Test with pytest and coverage
        run: |
          python -m pip install -U pytest coverage
          coverage --version
          coverage run -m pytest tests/ --ignore="tests/serving" -v --durations=20 --color=yes
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: CI
          name: python${{ matrix.python-version }}-test
          fail_ci_if_error: false
          verbose: true
