name: test install library

on:
  # Manual run
  workflow_dispatch:

jobs:
  build:
    name: test install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install nmslib
          python -m pip install dgl -f https://data.dgl.ai/wheels/repo.html
          python -m pip install -e .

      - name: Install dataclasses for python3.6
        run: python -m pip install dataclasses
        if: matrix.python-version == '3.6'

      - name: Test install
        run: python -c "import dgl; import nmslib; import libreco; print(libreco.__version__)"
